# Generated by Django 2.2 on 2019-05-03 13:01

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touroku',
            name='age',
        ),
        migrations.RemoveField(
            model_name='touroku',
            name='gender',
        ),
        migrations.AddField(
            model_name='touroku',
            name='asleeptime',
            field=models.TimeField(default=app1.models.default_start_time),
        ),
        migrations.AddField(
            model_name='touroku',
            name='awaketime',
            field=models.TimeField(default=app1.models.default_start_time),
        ),
        migrations.AddField(
            model_name='touroku',
            name='breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touroku',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日時'),
        ),
        migrations.AddField(
            model_name='touroku',
            name='dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touroku',
            name='drinking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touroku',
            name='eatout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touroku',
            name='kenkobody',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='touroku',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touroku',
            name='stretch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touroku',
            name='studying',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='touroku',
            name='workcond',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='touroku',
            name='workout',
            field=models.BooleanField(default=True),
        ),
    ]
